config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :fields
  resources :machines
  resources :chemicals
  resources :warehouses
  resources :employees
  resources :events
  authenticated :user do
    root 'fields#index', as: 'authenicated_root'
  end
  get 'calculator', to: 'pages#calculator'
  root 'pages#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chemical.rb
class Chemical < ApplicationRecord
  belongs_to :user
  has_many :events
end

app/models/employee.rb
class Employee < ApplicationRecord
  belongs_to :user
  has_many :events
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :chemical
  belongs_to :employee
  belongs_to :machine
  belongs_to :field
  belongs_to :user
end

app/models/field.rb
class Field < ApplicationRecord
  belongs_to :user
  has_many :events
  validates :number, presence: true
  validates :area, presence: true

  def is_own?
    if self.ownership
      'tak'
    else
      'nie'
    end
  end
end

app/models/machine.rb
class Machine < ApplicationRecord
  belongs_to :user
  has_many :events
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :fields
  has_many :machines
  has_many :chemicals
  has_many :warehouses
  has_many :employees
  has_many :events
end

app/models/warehouse.rb
class Warehouse < ApplicationRecord
  belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/chemicals_controller.rb
class ChemicalsController < ApplicationController
  before_action :find_chemical, only: %i[show edit update destroy same_user]
  before_action :authenticate_user!
  before_action :same_user, except: %i[index new create]

  def index
    @chemicals = Chemical.where(user_id: current_user)
  end

  def new
    @chemical = Chemical.new
  end

  def create 
    @chemical = current_user.chemicals.build(chemical_params)
    if @chemical.save
      redirect_to @chemical
    else
      render 'new'
    end
  end

  def show
  end

  def update
    if @chemical.update(chemical_params)
      redirect_to @chemical
    else
      render 'edit'
    end
  end

  def destroy
    @chemical.destroy
    redirect_to chemicals_path
  end

  private
    def find_chemical
      @chemical = Chemical.find(params[:id])
    end

    def chemical_params
      params.require(:chemical).permit(:expiration_date, :name, :volume, :volume_left)
    end

  def same_user
    return unless @chemical.user_id != current_user.id
      redirect_to chemicals_path
    end
  end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :find_employee, only: [:show, :edit, :update, :destroy]
  before_action :same_user, except: [:index, :new, :create]

  def index
    @employees = Employee.where(user_id: current_user)
  end

  def new
    @employee = Employee.new
  end

  def create 
    @employee = current_user.employees.build(employee_params)
    if @employee.save
      redirect_to @employee
    else
      render 'new'
    end
  end

  def show
  end

  def update
    if @employee.update(employee_params)
      redirect_to @employee
    else
      render 'edit'
    end
  end

  def destroy
    @employee.destroy
    redirect_to employees_path
  end


  private 
    def find_employee
      @employee = Employee.find(params[:id])
    end

    def employee_params
      params.require(:employee).permit(:name, :start_date, :payment, :skills)
    end

  def same_user
    return unless @employee.user_id != current_user.id
      redirect_to employees_path
    end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :find_event, only: %i[show edit update destroy same_user]
  before_action :authenticate_user!
  before_action :same_user, except: %i[index new create]

  def index
    @events = Event.where(user_id: current_user)
  end

  def new
    @event = Event.new
  end

  def create 
    @event = current_user.events.build(event_params)
    if @event.save
      redirect_to @event
    else
      render 'new'
    end
  end

  def show
  end

  def update
    if @event.update(event_params)
      redirect_to @event
    else
      render 'edit'
    end
  end

  def destroy
    @event.destroy
    redirect_to events_path
  end

  private
    def find_event
      @event = Event.find(params[:id])
    end

    def event_params
      params.require(:event).permit(:date, :time, :name, :chemical_id, :machine_id, :field_id, :employee_id)
    end

    def same_user
      if @event.user_id != current_user.id
        redirect_to events_path
      end
    end
end

app/controllers/fields_controller.rb
class FieldsController < ApplicationController
  before_action :find_field, only: [:show, :edit, :update, :destroy]
  before_action :same_user, except: [:index, :new, :create]

  def index
    @fields = Field.where(user_id: current_user)
  end

  def new
    @field = Field.new
  end

  def create 
    @field = current_user.fields.build(field_params)
    if @field.save
      redirect_to @field
    else
      render 'new'
    end
  end

  def show
  end

  def update
    if @field.update(field_params)
      redirect_to @field
    else
      render 'edit'
    end
  end

  def destroy
    @field.destroy
    redirect_to fields_path
  end

  private
    def find_field
      @field = Field.find(params[:id])
    end

    def field_params
      params.require(:field).permit(:year, :number, :area, :ownership, :name)
    end

    def same_user
      if @field.user_id != current_user.id
        redirect_to fields_path
      end
    end
end

app/controllers/machines_controller.rb
class MachinesController < ApplicationController
  before_action :find_machine, only: [:show, :edit, :update, :destroy]
  before_action :same_user, except: [:index, :new, :create]

  def index
    @machines = Machine.where(user_id: current_user)
  end

  def new
    @machine = Machine.new
  end

  def create 
    @machine = current_user.machines.build(machine_params)
    if @machine.save
      redirect_to @machine
    else
      render 'new'
    end
  end

  def show
  end

  def update
    if @machine.update(machine_params)
      redirect_to @machine
    else
      render 'edit'
    end
  end

  def destroy
    @machine.destroy
    redirect_to machines_path
  end

  private
    def find_machine
      @machine = Machine.find(params[:id])
    end

    def machine_params
      params.require(:machine).permit(:year, :name)
    end

    def same_user
      if @machine.user_id != current_user.id
        redirect_to machines_path
      end
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  def index
  end

  def calculator
    @warehouses = current_user.warehouses
    @employees = current_user.employees
    @chemicals = current_user.chemicals
  end
end

app/controllers/warehouses_controller.rb
class WarehousesController < ApplicationController
  before_action :find_warehouse, only: [:show, :edit, :update, :destroy]
  before_action :same_user, except: [:index, :new, :create]

  def index
    @warehouses = Warehouse.where(user_id: current_user)
  end

  def new
    @warehouse = Warehouse.new
  end

  def create 
    @warehouse = current_user.warehouses.build(warehouse_params)
    if @warehouse.save
      redirect_to @warehouse
    else
      render 'new'
    end
  end

  def show
  end

  def update
    if @warehouse.update(warehouse_params)
      redirect_to @warehouse
    else
      render 'edit'
    end
  end

  def destroy
    @warehouse.destroy
    redirect_to warehouses_path
  end

  private
    def find_warehouse
      @warehouse = Warehouse.find(params[:id])
    end

    def warehouse_params
      params.require(:warehouse).permit(:items, :name, :volume, :volume_left)
    end

    def same_user
      if @warehouse.user_id != current_user.id
        redirect_to warehouses_path
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chemicals_helper.rb
module ChemicalsHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/fields_helper.rb
module FieldsHelper
end

app/helpers/machines_helper.rb
module MachinesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/warehouses_helper.rb
module WarehousesHelper
end

app/views/chemicals/_form.html.haml
= render 'shared/errors', obj: @chemical

.row
  .col.s10.offset-s1
    =form_for @chemical do |f|
      .row
        .input-field.col.s12
          = f.label :name, 'Nazwa', class: 'active'
          = f.text_field :name, class: 'validate', autofocus: true
      .row
        .input-field.col.s12
          = f.label :expiration_date, 'Data przydatności', class: 'active'
          = f.date_field :expiration_date, class: 'validate'
      .row
        .input-field.col.s12
          = f.label :volume, 'Objętość [l]', class: 'active'
          = f.number_field :volume, class: 'validate'
      .row
        .input-field.col.s12
          = f.label :volume_left, 'Pozostała objętość [l]', class: 'active'
          = f.number_field :volume_left, class: 'validate'
      .row
        .input-field.col.s12
          = f.submit 'Dodaj', class: 'btn btn-success btn-lg'

app/views/chemicals/edit.html.haml
.center-align
  %h5 Edytuj substancję
  = render 'form'

app/views/chemicals/index.html.haml
%h4.center-align Substancje Chemiczne
%p.center-align
  =link_to 'Dodaj substancje', new_chemical_path
%ul.collection.col.s8.offset-s2
  - @chemicals.each do |chemical|
    %li.collection-item
      %p=link_to chemical.name, chemical_path(chemical)
      %p.grey-text Pozostało: #{chemical.volume_left}l

app/views/chemicals/new.html.haml
.center-align
  %h5 Nowa substancja
  = render 'form'

app/views/chemicals/show.html.haml
.row
  .col.s12.m8.offset-m2
    .card-panel.teal.center-align.white-text
      %h4 #{@chemical.name}
      %p Data ważności: #{@chemical.expiration_date.to_date}
      %p Objętość: #{@chemical.volume}l
      %p Pozostało: #{@chemical.volume_left}l
      %hr
      =link_to 'Usuń', @chemical, method: :delete, data: {confirm: 'Czy na pewno chcesz usunąć ten produkt?'}, class: 'white-text'
      =link_to 'Edytuj', edit_chemical_path, class: 'white-text'

app/views/employees/_form.html.haml
= render 'shared/errors', obj: @employee

.row
  .col.s10.offset-s1
    =form_for @employee do |f|
      .row
        .input-field.col.s12
          = f.label :name, 'Imię i Nazwisko', class: 'active'
          = f.text_field :name, class: 'validate', autofocus: true
      .row
        .input-field.col.s12
          = f.label :start_date, 'Data zatrudnienia', class: 'active'
          = f.date_field :start_date, class: 'validate'
      .row
        .input-field.col.s12
          = f.label :skills, 'Umiejętności', class: 'active'
          = f.text_field :skills, class: 'validate'
      .row
        .input-field.col.s12
          = f.label :payment, 'Stawka godzinowa', class: 'active'
          = f.number_field :payment, class: 'validate'
      .row
        .input-field.col.s12
          = f.submit 'Dodaj', class: 'btn btn-success btn-lg'

app/views/employees/edit.html.haml
.center-align
  %h5 Edytuj pracownika
  = render 'form'

app/views/employees/index.html.haml
%h4.center-align Pracownicy
%p.center-align
  =link_to 'Dodaj pracownika', new_employee_path
%ul.collection.col.s8.offset-s2
  - @employees.each do |employee|
    %li.collection-item
      %p=link_to employee.name, employee_path(employee)

app/views/employees/new.html.haml
.center-align
  %h5 Nowy pracownik
  = render 'form'

app/views/employees/show.html.haml
.row
  .col.s12.m8.offset-m2
    .card-panel.teal.center-align.white-text
      %h4 #{@employee.name}
      %p Umiejętności: #{@employee.skills}
      %p Data zatrudnienia: #{@employee.start_date.to_date}
      %p Stawka godzinowa: #{@employee.payment}PLN/H
      %hr
      =link_to 'Usuń', @employee, method: :delete, data: {confirm: 'Czy na pewno chcesz usunąć tego pracownika?'}, class: 'white-text'
      =link_to 'Edytuj', edit_employee_path, class: 'white-text'

app/views/fields/_form.html.haml
= render 'shared/errors', obj: @field

.row
  .col.s10.offset-s1
    =form_for @field do |f|
      .row
        .input-field.col.s12
          = f.label :name, 'Nazwa', class: 'active'
          = f.text_field :name, class: 'validate', autofocus: true
      .row
        .input-field.col.s12
          = f.label :number, 'Numer', class: 'active'
          = f.text_field :number, class: 'validate', autofocus: true
      .row
        .input-field.col.s12
          = f.label :area, 'Powierzchnia [ha]', class: 'active'
          = f.number_field :area, class: 'validate'
      .row
        .input-field.col.s12
          = f.label :year, 'Rok zakupu', class: 'active'
          = f.date_field :year, class: 'validate'
      .row
        .input-field.col.s12
          = f.label :ownership, 'Własność', class: 'active'
          = f.text_field :ownership, class: 'validate'
      .row
        .input-field.col.s12
          = f.submit 'Dodaj', class: 'btn btn-success btn-lg'

app/views/fields/edit.html.haml
.center-align
  %h5 Edytuj pole
  = render 'form'

app/views/fields/index.html.haml
%h4.center-align Twoje pola
%p.center-align
  =link_to 'Dodaj pole', new_field_path
%ul.collection.col.s8.offset-s2
  - @fields.each do |field|
    %li.collection-item
      %p=link_to field.name, field_path(field)

app/views/fields/new.html.haml
.center-align
  %h5 Nowe pole
  = render 'form'

app/views/fields/show.html.haml
.row
  .col.s12.m10.offset-m1
    .card-panel.teal.center-align.white-text
      %h4 #{@field.name}
      =link_to 'Usuń', @field, method: :delete, data: {confirm: 'Czy na pewno chcesz usunąć to pole?'}, class: 'white-text'
      =link_to 'Edytuj', edit_field_path, class: 'white-text'
      %hr
      .row
        .col.s6
          %p Numer pola: #{@field.number}
          %p Rok zakupu: #{@field.year.to_date}
        .col.s6
          %p Własność: #{@field.is_own?}
          %p Powierzchnia: #{@field.area} ha
      %hr
      .row
        .col.s12
          =render 'shared/collection', obj: @field.events, keys: [:name, :date, :time]

app/views/machines/_form.html.haml
= render 'shared/errors', obj: @machine

.row
  .col.s10.offset-s1
    =form_for @machine do |f|
      .row
        .input-field.col.s12
          = f.label :name, 'Nazwa', class: 'active'
          = f.text_field :name, class: 'validate', autofocus: true
      .row
        .input-field.col.s12
          = f.label :year, 'Rok maszyny', class: 'active'
          = f.date_field :year, class: 'validate'
      .row
        .input-field.col.s12
          = f.submit 'Dodaj', class: 'btn btn-success btn-lg'

app/views/machines/edit.html.haml
.center-align
  %h5 Edytuj maszynę
  = render 'form'

app/views/machines/index.html.haml
%h4.center-align Twoje maszyny
%p.center-align
  =link_to 'Dodaj maszynę', new_machine_path
%ul.collection.col.s8.offset-s2
  - @machines.each do |machine|
    %li.collection-item
      %p=link_to machine.name, machine

app/views/machines/new.html.haml
.center-align
  %h5 Dodaj maszynę
  = render 'form'

app/views/machines/show.html.haml
.row
  .col.s12.m8.offset-m2
    .card-panel.teal.center-align.white-text
      %h4 #{@machine.name}
      %p Rok zakupu: #{@machine.year.to_date}
      %hr
      =link_to 'Usuń', @machine, method: :delete, data: {confirm: 'Czy na pewno chcesz usunąć tę maszynę?'}, class: 'white-text'
      =link_to 'Edytuj', edit_machine_path, class: 'white-text'