config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :fields
  resources :machines
  resources :chemicals
  resources :warehouses
  resources :employees
  resources :events
  authenticated :user do
    root 'fields#index', as: 'authenicated_root'
  end
  get 'calculator', to: 'pages#calculator'
  root 'pages#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chemical.rb
class Chemical < ApplicationRecord
  belongs_to :user
  has_many :events
end

app/models/employee.rb
class Employee < ApplicationRecord
  belongs_to :user
  has_many :events
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :chemical
  belongs_to :employee
  belongs_to :machine
  belongs_to :field
  belongs_to :user
end

app/models/field.rb
class Field < ApplicationRecord
  belongs_to :user
  has_many :events
  validates :number, presence: true
  validates :area, presence: true

  def is_own?
    if self.ownership
      'tak'
    else
      'nie'
    end
  end
end

app/models/machine.rb
class Machine < ApplicationRecord
  belongs_to :user
  has_many :events
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :fields
  has_many :machines
  has_many :chemicals
  has_many :warehouses
  has_many :employees
  has_many :events
end

app/models/warehouse.rb
class Warehouse < ApplicationRecord
  belongs_to :user
end

app/controllers/chemicals_controller.rb
class ChemicalsController < ApplicationController
  before_action :find_chemical, only: %i[show edit update destroy same_user]
  before_action :authenticate_user!
  before_action :same_user, except: %i[index new create]

  def index
    @chemicals = Chemical.where(user_id: current_user)
  end

  def new
    @chemical = Chemical.new
  end

  def create 
    @chemical = current_user.chemicals.build(chemical_params)
    if @chemical.save
      redirect_to @chemical
    else
      render 'new'
    end
  end

  def show
  end

  def update
    if @chemical.update(chemical_params)
      redirect_to @chemical
    else
      render 'edit'
    end
  end

  def destroy
    @chemical.destroy
    redirect_to chemicals_path
  end

  private
    def find_chemical
      @chemical = Chemical.find(params[:id])
    end

    def chemical_params
      params.require(:chemical).permit(:expiration_date, :name, :volume, :volume_left)
    end

  def same_user
    return unless @chemical.user_id != current_user.id
      redirect_to chemicals_path
    end
  end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :find_employee, only: [:show, :edit, :update, :destroy]
  before_action :same_user, except: [:index, :new, :create]

  def index
    @employees = Employee.where(user_id: current_user)
  end

  def new
    @employee = Employee.new
  end

  def create 
    @employee = current_user.employees.build(employee_params)
    if @employee.save
      redirect_to @employee
    else
      render 'new'
    end
  end

  def show
  end

  def update
    if @employee.update(employee_params)
      redirect_to @employee
    else
      render 'edit'
    end
  end

  def destroy
    @employee.destroy
    redirect_to employees_path
  end


  private 
    def find_employee
      @employee = Employee.find(params[:id])
    end

    def employee_params
      params.require(:employee).permit(:name, :start_date, :payment, :skills)
    end

  def same_user
    return unless @employee.user_id != current_user.id
      redirect_to employees_path
    end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :find_event, only: %i[show edit update destroy same_user]
  before_action :authenticate_user!
  before_action :same_user, except: %i[index new create]

  def index
    @events = Event.where(user_id: current_user)
  end

  def new
    @event = Event.new
  end

  def create 
    @event = current_user.events.build(event_params)
    if @event.save
      redirect_to @event
    else
      render 'new'
    end
  end

  def show
  end

  def update
    if @event.update(event_params)
      redirect_to @event
    else
      render 'edit'
    end
  end

  def destroy
    @event.destroy
    redirect_to events_path
  end

  private
    def find_event
      @event = Event.find(params[:id])
    end

    def event_params
      params.require(:event).permit(:date, :time, :name, :chemical_id, :machine_id, :field_id, :employee_id)
    end

    def same_user
      if @event.user_id != current_user.id
        redirect_to events_path
      end
    end
end

app/controllers/fields_controller.rb
class FieldsController < ApplicationController
  before_action :find_field, only: [:show, :edit, :update, :destroy]
  before_action :same_user, except: [:index, :new, :create]

  def index
    @fields = Field.where(user_id: current_user)
  end

  def new
    @field = Field.new
  end

  def create 
    @field = current_user.fields.build(field_params)
    if @field.save
      redirect_to @field
    else
      render 'new'
    end
  end

  def show
  end

  def update
    if @field.update(field_params)
      redirect_to @field
    else
      render 'edit'
    end
  end

  def destroy
    @field.destroy
    redirect_to fields_path
  end

  private
    def find_field
      @field = Field.find(params[:id])
    end

    def field_params
      params.require(:field).permit(:year, :number, :area, :ownership, :name)
    end

    def same_user
      if @field.user_id != current_user.id
        redirect_to fields_path
      end
    end
end

app/controllers/machines_controller.rb
class MachinesController < ApplicationController
  before_action :find_machine, only: [:show, :edit, :update, :destroy]
  before_action :same_user, except: [:index, :new, :create]

  def index
    @machines = Machine.where(user_id: current_user)
  end

  def new
    @machine = Machine.new
  end

  def create 
    @machine = current_user.machines.build(machine_params)
    if @machine.save
      redirect_to @machine
    else
      render 'new'
    end
  end

  def show
  end

  def update
    if @machine.update(machine_params)
      redirect_to @machine
    else
      render 'edit'
    end
  end

  def destroy
    @machine.destroy
    redirect_to machines_path
  end

  private
    def find_machine
      @machine = Machine.find(params[:id])
    end

    def machine_params
      params.require(:machine).permit(:year, :name)
    end

    def same_user
      if @machine.user_id != current_user.id
        redirect_to machines_path
      end
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  def index
  end

  def calculator
    @warehouses = current_user.warehouses
    @employees = current_user.employees
    @chemicals = current_user.chemicals
  end
end

app/controllers/warehouses_controller.rb
class WarehousesController < ApplicationController
  before_action :find_warehouse, only: [:show, :edit, :update, :destroy]
  before_action :same_user, except: [:index, :new, :create]

  def index
    @warehouses = Warehouse.where(user_id: current_user)
  end

  def new
    @warehouse = Warehouse.new
  end

  def create 
    @warehouse = current_user.warehouses.build(warehouse_params)
    if @warehouse.save
      redirect_to @warehouse
    else
      render 'new'
    end
  end

  def show
  end

  def update
    if @warehouse.update(warehouse_params)
      redirect_to @warehouse
    else
      render 'edit'
    end
  end

  def destroy
    @warehouse.destroy
    redirect_to warehouses_path
  end

  private
    def find_warehouse
      @warehouse = Warehouse.find(params[:id])
    end

    def warehouse_params
      params.require(:warehouse).permit(:items, :name, :volume, :volume_left)
    end

    def same_user
      if @warehouse.user_id != current_user.id
        redirect_to warehouses_path
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chemicals_helper.rb
module ChemicalsHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/fields_helper.rb
module FieldsHelper
end

app/helpers/machines_helper.rb
module MachinesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/warehouses_helper.rb
module WarehousesHelper
end

app/views/events/_form.html.haml
= render 'shared/errors', obj: @event

.row
  .col.s10.offset-s1
    =form_for @event do |f|
      .row
        .input-field.col.s12
          = f.label :name, 'Nazwa', class: 'active'
          = f.text_field :name, class: 'validate', autofocus: true, class: 'active'
      .row
        .input-field.col.s12
          = f.label :machine_id, 'Maszyna', class: 'active'
          = f.select :machine_id, options_for_select(Machine.where(user_id: current_user).map{|s|[s.name, s.id]})
      .row
        .input-field.col.s12
          = f.label :chemical_id, 'Chemikalia', class: 'active'
          = f.select :chemical_id, options_for_select(Chemical.where(user_id: current_user).map{|s|[s.name, s.id]})
      .row
        .input-field.col.s12
          = f.label :field_id, 'Pole', class: 'active'
          = f.select :field_id, options_for_select(Field.where(user_id: current_user).map{|s|[s.name, s.id]})
      .row
        .input-field.col.s12
          = f.label :employee_id, 'Pracownik', class: 'active'
          = f.select :employee_id, options_for_select(Employee.where(user_id: current_user).map{|s|[s.name, s.id]})
      .row
        .input-field.col.s12
          = f.label :date, 'Data', class: 'active'
          = f.date_field :date, class: 'validate', autofocus: true, class: 'active'
      .row
        .input-field.col.s12
          = f.label :time, 'Czas', class: 'active'
          = f.time_field :time, class: 'validate', autofocus: true, class: 'active'
      .row
        .input-field.col.s12
          = f.submit 'Dodaj', class: 'btn btn-success btn-lg'

app/views/events/edit.html.haml
.center-align
  %h5 Edytuj akcję
  = render 'form'

app/views/events/index.html.haml
%h4.center-align Akcje
%p.center-align
  =link_to 'Dodaj akcję', new_event_path
%ul.collection.col.s8.offset-s2
  - @events.each do |event|
    %li.collection-item
      %p=link_to event.name, event_path(event)

app/views/events/new.html.haml
.center-align
  %h5 Nowa akcja
  = render 'form'

app/views/warehouses/_form.html.haml
= render 'shared/errors', obj: @warehouse

.row
  .col.s10.offset-s1
    =form_for @warehouse do |f|
      .row
        .input-field.col.s12
          = f.label :name, 'Nazwa', class: 'active'
          = f.text_field :name, class: 'validate', autofocus: true
      .row
        .input-field.col.s12
          = f.label :items, 'Przechowywane rośliny', class: 'active'
          = f.text_field :items, class: 'validate', autofocus: true
      .row
        .input-field.col.s12
          = f.label :volume, 'Objętość [l]', class: 'active'
          = f.number_field :volume, class: 'validate'
      .row
        .input-field.col.s12
          = f.label :volume_left, 'Pozostała objętość [l]', class: 'active'
          = f.number_field :volume_left, class: 'validate'
      .row
        .input-field.col.s12
          = f.submit 'Dodaj', class: 'btn btn-success btn-lg'

app/views/warehouses/edit.html.haml
.center-align
  %h5 Edytuj magazyn
  = render 'form'

app/views/warehouses/index.html.haml
%h4.center-align Magazyny
%p.center-align
  =link_to 'Dodaj magazyn', new_warehouse_path
%ul.collection.col.s8.offset-s2
  - @warehouses.each do |warehouse|
    %li.collection-item
      %p=link_to warehouse.name, warehouse_path(warehouse)
      %p.grey-text Rośliny: #{warehouse.items} | Pozostało: #{warehouse.volume_left}l

app/views/warehouses/new.html.haml
.center-align
  %h5 Dodaj magazyn
  = render 'form'

app/views/warehouses/show.html.haml
.row
  .col.s12.m8.offset-m2
    .card-panel.teal.center-align.white-text
      %h4 #{@warehouse.name}
      %p Przechowywane rośliny: #{@warehouse.items}
      %p Objętość: #{@warehouse.volume}
      %p Pozostało: #{@warehouse.volume_left}
      %hr
      =link_to 'Usuń', @warehouse, method: :delete, data: {confirm: 'Czy na pewno chcesz usunąć ten magazyn?'}, class: 'white-text'
      =link_to 'Edytuj', edit_warehouse_path, class: 'white-text'