config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :fields
  resources :machines
  resources :chemicals
  resources :warehouses
  resources :employees
  resources :events
  authenticated :user do
    root 'fields#index', as: 'authenicated_root'
  end
  get 'calculator', to: 'pages#calculator'
  root 'pages#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chemical.rb
class Chemical < ApplicationRecord
  belongs_to :user
  has_many :events
end

app/models/employee.rb
class Employee < ApplicationRecord
  belongs_to :user
  has_many :events
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :chemical
  belongs_to :employee
  belongs_to :machine
  belongs_to :field
  belongs_to :user
end

app/models/field.rb
class Field < ApplicationRecord
  belongs_to :user
  has_many :events
  validates :number, presence: true
  validates :area, presence: true

  def is_own?
    if self.ownership
      'tak'
    else
      'nie'
    end
  end
end

app/models/machine.rb
class Machine < ApplicationRecord
  belongs_to :user
  has_many :events
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :fields
  has_many :machines
  has_many :chemicals
  has_many :warehouses
  has_many :employees
  has_many :events
end

app/models/warehouse.rb
class Warehouse < ApplicationRecord
  belongs_to :user
end

app/controllers/chemicals_controller.rb
class ChemicalsController < ApplicationController
  before_action :find_chemical, only: %i[show edit update destroy same_user]
  before_action :authenticate_user!
  before_action :same_user, except: %i[index new create]

  def index
    @chemicals = Chemical.where(user_id: current_user)
  end

  def new
    @chemical = Chemical.new
  end

  def create 
    @chemical = current_user.chemicals.build(chemical_params)
    if @chemical.save
      redirect_to @chemical
    else
      render 'new'
    end
  end

  def show
  end

  def update
    if @chemical.update(chemical_params)
      redirect_to @chemical
    else
      render 'edit'
    end
  end

  def destroy
    @chemical.destroy
    redirect_to chemicals_path
  end

  private
    def find_chemical
      @chemical = Chemical.find(params[:id])
    end

    def chemical_params
      params.require(:chemical).permit(:expiration_date, :name, :volume, :volume_left)
    end

  def same_user
    return unless @chemical.user_id != current_user.id
      redirect_to chemicals_path
    end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :find_event, only: %i[show edit update destroy same_user]
  before_action :authenticate_user!
  before_action :same_user, except: %i[index new create]

  def index
    @events = Event.where(user_id: current_user)
  end

  def new
    @event = Event.new
  end

  def create 
    @event = current_user.events.build(event_params)
    if @event.save
      redirect_to @event
    else
      render 'new'
    end
  end

  def show
  end

  def update
    if @event.update(event_params)
      redirect_to @event
    else
      render 'edit'
    end
  end

  def destroy
    @event.destroy
    redirect_to events_path
  end

  private
    def find_event
      @event = Event.find(params[:id])
    end

    def event_params
      params.require(:event).permit(:date, :time, :name, :chemical_id, :machine_id, :field_id, :employee_id)
    end

    def same_user
      if @event.user_id != current_user.id
        redirect_to events_path
      end
    end
end

app/controllers/fields_controller.rb
class FieldsController < ApplicationController
  before_action :find_field, only: [:show, :edit, :update, :destroy]
  before_action :same_user, except: [:index, :new, :create]

  def index
    @fields = Field.where(user_id: current_user)
  end

  def new
    @field = Field.new
  end

  def create 
    @field = current_user.fields.build(field_params)
    if @field.save
      redirect_to @field
    else
      render 'new'
    end
  end

  def show
  end

  def update
    if @field.update(field_params)
      redirect_to @field
    else
      render 'edit'
    end
  end

  def destroy
    @field.destroy
    redirect_to fields_path
  end

  private
    def find_field
      @field = Field.find(params[:id])
    end

    def field_params
      params.require(:field).permit(:year, :number, :area, :ownership, :name)
    end

    def same_user
      if @field.user_id != current_user.id
        redirect_to fields_path
      end
    end
end

app/controllers/machines_controller.rb
class MachinesController < ApplicationController
  before_action :find_machine, only: [:show, :edit, :update, :destroy]
  before_action :same_user, except: [:index, :new, :create]

  def index
    @machines = Machine.where(user_id: current_user)
  end

  def new
    @machine = Machine.new
  end

  def create 
    @machine = current_user.machines.build(machine_params)
    if @machine.save
      redirect_to @machine
    else
      render 'new'
    end
  end

  def show
  end

  def update
    if @machine.update(machine_params)
      redirect_to @machine
    else
      render 'edit'
    end
  end

  def destroy
    @machine.destroy
    redirect_to machines_path
  end

  private
    def find_machine
      @machine = Machine.find(params[:id])
    end

    def machine_params
      params.require(:machine).permit(:year, :name)
    end

    def same_user
      if @machine.user_id != current_user.id
        redirect_to machines_path
      end
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  def index
  end

  def calculator
    @warehouses = current_user.warehouses
    @employees = current_user.employees
    @chemicals = current_user.chemicals
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chemicals_helper.rb
module ChemicalsHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/fields_helper.rb
module FieldsHelper
end

app/helpers/machines_helper.rb
module MachinesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/warehouses_helper.rb
module WarehousesHelper
end

app/views/layouts/_flash.html.haml
%p.notice= notice
%p.alert= alert

app/views/layouts/_nav.html.haml
%nav
  %a.brand-logo FARMER
  %a.sidenav-trigger{"data-target" => "mobile"}
    %i.material-icons menu
  %ul.right.hide-on-med-and-down
    - if user_signed_in?
      =link_to 'WYLOGUJ', destroy_user_session_path, method: :delete
    - else
      =link_to 'ZALOGUJ', new_user_session_path
      =link_to 'ZAREJESTRUJ', new_user_registration_path
  %ul.sidenav#mobile
    - if user_signed_in?
      =link_to 'POLA', fields_path
      =link_to 'MASZYNY', machines_path
      =link_to 'CHEMIKALIA', chemicals_path
      =link_to 'MAGAZYNY', warehouses_path
      %li WYDATKI
      =link_to 'AKCJE', events_path
      =link_to 'PRACOWNICY', employees_path
      =link_to 'KALKULATOR', calculator_path
      =link_to 'WYLOGUJ', destroy_user_session_path, method: :delete
    - else
      =link_to 'ZALOGUJ', new_user_session_path
      =link_to 'ZAREJESTRUJ', new_user_registration_path

app/views/layouts/_sidebar.html.haml
.col.hide-on-med-and-down.l2.sidebar
  %ul
    %li=link_to 'POLA', fields_path
    %li=link_to 'MASZYNY', machines_path
    %li=link_to 'CHEMIKALIA', chemicals_path
    %li=link_to 'MAGAZYNY', warehouses_path
    %li WYDATKI
    %li=link_to 'AKCJE', events_path
    %li=link_to 'PRACOWNICY', employees_path
    %li=link_to 'KALKULATOR', calculator_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FarmerApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/nav'%>
    <main>
      <div class="row">
        <% if user_signed_in? %>
          <%= render 'layouts/sidebar' %>
        <% end %>
        <div class="col offset-l2 s12 m12 l10 page">
          <%= render 'layouts/flash' %>
          <%= yield %>
        </div>
      </div>
    </main>
  </body>
</html>

app/views/pages/calculator.html.haml
.center-align
  %h4 KALKULATORY
  %br
  .row
    .col.s12.m4.calculator
      %h5 Wypłaty
      .row
        .col.s10.offset-s1
          %br
          = label_tag :number_w, 'Liczba Godzin'
          = number_field_tag :number_w, 0, step: 0.5
          = label_tag :value_W, 'Stawka Pracownika'
          = number_field_tag :value_w, 0
          = label_tag :result_w, 'Wynik'
          %h5#result_w 0
          %br
          = submit_tag 'Oblicz', class: 'btn', onclick: 'count_payment()'
    .col.s12.m4.calculator
      %h5 Chemikalia
      .row
        .col.s10.offset-s1
          %br
          = label_tag :area_c, 'Liczba hektarów'
          = number_field_tag :area_c, 0, step: 0.1
          = label_tag :chemical_c, 'Wydajność substancji [l/ha]'
          = number_field_tag :chemical_c, 0, step: 0.1
          = label_tag :result_c, 'Liczba potrzebnych litrów'
          %h5#result_c 0
          %br
          = submit_tag 'Oblicz', class: 'btn', onclick: 'count_chemicals()'
    .col.s12.m4.calculator
      %h5 Magazyn
      .row
        .col.s10.offset-s1
          %br
          = label_tag :area_m, 'Liczba hektarów'
          = number_field_tag :area_m, 0, step: 0.1
          = label_tag :items_m, 'Wydajność zbiorów [l/ha]'
          = number_field_tag :items_m, 0, step: 0.1
          = label_tag :result_m, 'Liczba potrzebnych litrów'
          %h5#result_m 0
          %br
          = submit_tag 'Oblicz', class: 'btn', onclick: 'count_magazins()'

app/views/pages/index.html.haml
%h1 Cześć!

app/views/shared/_collection.html.haml
%ul.collection
  %li.collection-header
    %h5 Historia
  -obj.sort_by(&:date).reverse.each do |el|
    %li.collection-item.black-text
      =link_to  "#{el.name} | #{el.date} | #{el.time.strftime('%H:%M')} | #{el.machine.name} | #{el.employee.name} | #{el.chemical.name} ", event_path(el)

app/views/shared/_errors.html.haml
- if obj.errors.any? 
  .errors
    .card-content
      %h4.panel-title= pluralize(obj.errors.count, 'error')
    .card-action
      %ul
        - obj.errors.full_messages.each do |msg|
          %li= msg

app/views/shared/_table.html.haml
.table
  .thead
    .tr
      -keys.each do |k|
        .td #{k}
  .tbody
  -obj.each do |el|
    .tr
      -keys.each do |k|
        .td #{el[k]}